### Get all RSS feeds (no content)

GET http://localhost:3000/rss HTTP/2.0

### Get a feed and content

GET http://localhost:3000/rss/66a0170dce04dbb45e468c0e HTTP/2.0

### Add an RSS feed to db

POST http://localhost:3000/rss HTTP/2.0
content-type: application/json

{
  "source": "https://news.ycombinator.com/rss"
}

### Delete an RSS feed from db

DELETE http://localhost:3000/rss/66a0170dce04dbb45e468c0e HTTP/2.0