### Get all RSS feeds (no content)

GET http://localhost:3000/rss HTTP/2.0

### Get a feed and content

GET http://localhost:3000/rss/66a297f2a1d87f43fa6a1ab5 HTTP/2.0

### Add an RSS feed to db

POST http://localhost:3000/rss HTTP/2.0
content-type: application/json

{
  "source": "https://news.ycombinator.com/rss"
}

### Delete an RSS feed from db

DELETE http://localhost:3000/rss/66a29726d6976a371055a326 HTTP/2.0